#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/notice?serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: Rhksgh12!
#
#  jpa:
#    show-sql: true
#    hibernate:
#      format_sql: true
#      ddl-auto: update
#
#  logging:
#    level:
#      org:
#        hibernate:
#          SQL: DEBUG
#          type:
#            trace
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notice?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Rhksgh12!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
